ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STANDARD';
ALTER TYPE "AppRole" ADD VALUE IF NOT EXISTS 'artist';
ALTER TYPE "AppRole" ADD VALUE IF NOT EXISTS 'standard';
ALTER TYPE "ProjectRole" ADD VALUE IF NOT EXISTS 'artist';
ALTER TYPE "ProjectRole" ADD VALUE IF NOT EXISTS 'standard';
